//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRegInfoSet
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int No { get; set; }
        public decimal AgentPercentSSC { get; set; }
        public decimal AgentPercent11X5 { get; set; }
        public decimal AgentPercentDPC { get; set; }
    }
}
