//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountWithdraw
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string BankName { get; set; }
        public string BankCardNo { get; set; }
        public string OrderNo { get; set; }
        public decimal Money { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Remarks { get; set; }
        public int Status { get; set; }
        public bool isAutoPay { get; set; }
        public string auditor { get; set; }
        public Nullable<System.DateTime> auditTime { get; set; }
    }
}
