//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCard
    {
        public int AccountId { get; set; }
        public int No { get; set; }
        public string BankName { get; set; }
        public string CardNo { get; set; }
        public System.DateTime CreatTime { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string OpenCardName { get; set; }
        public Nullable<int> CityId { get; set; }
        public string BankNo { get; set; }
        public string BankChildName { get; set; }
    
        public virtual Accounts Accounts { get; set; }
    }
}
