//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotteryPrizePoolInfo
    {
        public long LotteryOpenId { get; set; }
        public decimal TotalBet { get; set; }
        public decimal TotalBack { get; set; }
        public decimal TotalAgenBack { get; set; }
        public decimal Profit { get; set; }
    
        public virtual LotteryOpenInfo LotteryOpenInfo { get; set; }
    }
}
