//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotterys
    {
        public Lotterys()
        {
            this.LotteryOffcialSchedule = new HashSet<LotteryOffcialSchedule>();
            this.LotteryOpenInfo = new HashSet<LotteryOpenInfo>();
        }
    
        public int Id { get; set; }
        public string LotteryName { get; set; }
        public string LotteryType { get; set; }
        public string LotteryCode { get; set; }
        public bool IsPrivate { get; set; }
        public Nullable<decimal> TimeStart { get; set; }
        public Nullable<decimal> TimeEnd { get; set; }
        public Nullable<decimal> BetweenMinute { get; set; }
        public Nullable<int> ExceptLength { get; set; }
        public Nullable<int> ExceptOneDay { get; set; }
    
        public virtual ICollection<LotteryOffcialSchedule> LotteryOffcialSchedule { get; set; }
        public virtual ICollection<LotteryOpenInfo> LotteryOpenInfo { get; set; }
    }
}
