//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinglePay_Record
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public string merchantId { get; set; }
        public string orderNO { get; set; }
        public string orderDatetime { get; set; }
        public string accountNo { get; set; }
        public string accountName { get; set; }
        public string accountType { get; set; }
        public string bankNo { get; set; }
        public string bankName { get; set; }
        public decimal amt { get; set; }
        public string ext1 { get; set; }
        public string ext2 { get; set; }
        public byte signlePay_status { get; set; }
        public string singlePaydatetime { get; set; }
        public Nullable<System.DateTime> creationTime { get; set; }
    }
}
