//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST1.SR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://XY.org/")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountPwdField;
        
        private decimal AccountBalanceField;
        
        private int AccountParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNicknameField;
        
        private decimal AgentPercentSSCField;
        
        private decimal AgentPercent11X5Field;
        
        private decimal AgentPercentDPCField;
        
        private System.DateTime CreateTimeField;
        
        private int AccountStatusField;
        
        private int LoginCountField;
        
        private System.Nullable<System.DateTime> LastLoginField;
        
        private bool BankCardLockStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountPwd {
            get {
                return this.AccountPwdField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountPwdField, value) != true)) {
                    this.AccountPwdField = value;
                    this.RaisePropertyChanged("AccountPwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal AccountBalance {
            get {
                return this.AccountBalanceField;
            }
            set {
                if ((this.AccountBalanceField.Equals(value) != true)) {
                    this.AccountBalanceField = value;
                    this.RaisePropertyChanged("AccountBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int AccountParentId {
            get {
                return this.AccountParentIdField;
            }
            set {
                if ((this.AccountParentIdField.Equals(value) != true)) {
                    this.AccountParentIdField = value;
                    this.RaisePropertyChanged("AccountParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AccountNickname {
            get {
                return this.AccountNicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNicknameField, value) != true)) {
                    this.AccountNicknameField = value;
                    this.RaisePropertyChanged("AccountNickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal AgentPercentSSC {
            get {
                return this.AgentPercentSSCField;
            }
            set {
                if ((this.AgentPercentSSCField.Equals(value) != true)) {
                    this.AgentPercentSSCField = value;
                    this.RaisePropertyChanged("AgentPercentSSC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal AgentPercent11X5 {
            get {
                return this.AgentPercent11X5Field;
            }
            set {
                if ((this.AgentPercent11X5Field.Equals(value) != true)) {
                    this.AgentPercent11X5Field = value;
                    this.RaisePropertyChanged("AgentPercent11X5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal AgentPercentDPC {
            get {
                return this.AgentPercentDPCField;
            }
            set {
                if ((this.AgentPercentDPCField.Equals(value) != true)) {
                    this.AgentPercentDPCField = value;
                    this.RaisePropertyChanged("AgentPercentDPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int AccountStatus {
            get {
                return this.AccountStatusField;
            }
            set {
                if ((this.AccountStatusField.Equals(value) != true)) {
                    this.AccountStatusField = value;
                    this.RaisePropertyChanged("AccountStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int LoginCount {
            get {
                return this.LoginCountField;
            }
            set {
                if ((this.LoginCountField.Equals(value) != true)) {
                    this.LoginCountField = value;
                    this.RaisePropertyChanged("LoginCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<System.DateTime> LastLogin {
            get {
                return this.LastLoginField;
            }
            set {
                if ((this.LastLoginField.Equals(value) != true)) {
                    this.LastLoginField = value;
                    this.RaisePropertyChanged("LastLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool BankCardLockStatus {
            get {
                return this.BankCardLockStatusField;
            }
            set {
                if ((this.BankCardLockStatusField.Equals(value) != true)) {
                    this.BankCardLockStatusField = value;
                    this.RaisePropertyChanged("BankCardLockStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WS_Lotterys", Namespace="http://XY.org/")]
    [System.SerializableAttribute()]
    public partial class WS_Lotterys : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotteryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotteryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotteryCodeField;
        
        private bool IsPrivateField;
        
        private System.Nullable<decimal> TimeStartField;
        
        private System.Nullable<decimal> TimeEndField;
        
        private System.Nullable<int> BetweenMinuteField;
        
        private System.Nullable<int> ExceptLengthField;
        
        private System.Nullable<int> ExceptOneDayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LotteryName {
            get {
                return this.LotteryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LotteryNameField, value) != true)) {
                    this.LotteryNameField = value;
                    this.RaisePropertyChanged("LotteryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LotteryType {
            get {
                return this.LotteryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LotteryTypeField, value) != true)) {
                    this.LotteryTypeField = value;
                    this.RaisePropertyChanged("LotteryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LotteryCode {
            get {
                return this.LotteryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LotteryCodeField, value) != true)) {
                    this.LotteryCodeField = value;
                    this.RaisePropertyChanged("LotteryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> TimeStart {
            get {
                return this.TimeStartField;
            }
            set {
                if ((this.TimeStartField.Equals(value) != true)) {
                    this.TimeStartField = value;
                    this.RaisePropertyChanged("TimeStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> TimeEnd {
            get {
                return this.TimeEndField;
            }
            set {
                if ((this.TimeEndField.Equals(value) != true)) {
                    this.TimeEndField = value;
                    this.RaisePropertyChanged("TimeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> BetweenMinute {
            get {
                return this.BetweenMinuteField;
            }
            set {
                if ((this.BetweenMinuteField.Equals(value) != true)) {
                    this.BetweenMinuteField = value;
                    this.RaisePropertyChanged("BetweenMinute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> ExceptLength {
            get {
                return this.ExceptLengthField;
            }
            set {
                if ((this.ExceptLengthField.Equals(value) != true)) {
                    this.ExceptLengthField = value;
                    this.RaisePropertyChanged("ExceptLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> ExceptOneDay {
            get {
                return this.ExceptOneDayField;
            }
            set {
                if ((this.ExceptOneDayField.Equals(value) != true)) {
                    this.ExceptOneDayField = value;
                    this.RaisePropertyChanged("ExceptOneDay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LotteryPlays", Namespace="http://XY.org/")]
    [System.SerializableAttribute()]
    public partial class LotteryPlays : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotteryTypeField;
        
        private int LotteryPlayIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotteryPlayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrizeClassField;
        
        private System.Nullable<decimal> PayBackField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LotteryType {
            get {
                return this.LotteryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LotteryTypeField, value) != true)) {
                    this.LotteryTypeField = value;
                    this.RaisePropertyChanged("LotteryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int LotteryPlayId {
            get {
                return this.LotteryPlayIdField;
            }
            set {
                if ((this.LotteryPlayIdField.Equals(value) != true)) {
                    this.LotteryPlayIdField = value;
                    this.RaisePropertyChanged("LotteryPlayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LotteryPlayName {
            get {
                return this.LotteryPlayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LotteryPlayNameField, value) != true)) {
                    this.LotteryPlayNameField = value;
                    this.RaisePropertyChanged("LotteryPlayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PrizeClass {
            get {
                return this.PrizeClassField;
            }
            set {
                if ((object.ReferenceEquals(this.PrizeClassField, value) != true)) {
                    this.PrizeClassField = value;
                    this.RaisePropertyChanged("PrizeClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> PayBack {
            get {
                return this.PayBackField;
            }
            set {
                if ((this.PayBackField.Equals(value) != true)) {
                    this.PayBackField = value;
                    this.RaisePropertyChanged("PayBack");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://XY.org/", ConfigurationName="SR.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://XY.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://XY.org/HelloWorld", ReplyAction="*")]
        TEST1.SR.HelloWorldResponse HelloWorld(TEST1.SR.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://XY.org/ 的元素名称 Guid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://XY.org/LoginOn", ReplyAction="*")]
        TEST1.SR.LoginOnResponse LoginOn(TEST1.SR.LoginOnRequest request);
        
        // CODEGEN: 命名空间 http://XY.org/ 的元素名称 Guid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://XY.org/GetAccountInfo", ReplyAction="*")]
        TEST1.SR.GetAccountInfoResponse GetAccountInfo(TEST1.SR.GetAccountInfoRequest request);
        
        // CODEGEN: 命名空间 http://XY.org/ 的元素名称 Guid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://XY.org/GetLotteryList", ReplyAction="*")]
        TEST1.SR.GetLotteryListResponse GetLotteryList(TEST1.SR.GetLotteryListRequest request);
        
        // CODEGEN: 命名空间 http://XY.org/ 的元素名称 Guid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://XY.org/GetLotteryPlayList", ReplyAction="*")]
        TEST1.SR.GetLotteryPlayListResponse GetLotteryPlayList(TEST1.SR.GetLotteryPlayListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://XY.org/", Order=0)]
        public TEST1.SR.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TEST1.SR.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://XY.org/", Order=0)]
        public TEST1.SR.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TEST1.SR.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://XY.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginOnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginOn", Namespace="http://XY.org/", Order=0)]
        public TEST1.SR.LoginOnRequestBody Body;
        
        public LoginOnRequest() {
        }
        
        public LoginOnRequest(TEST1.SR.LoginOnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://XY.org/")]
    public partial class LoginOnRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Pwd;
        
        public LoginOnRequestBody() {
        }
        
        public LoginOnRequestBody(string Guid, string Name, string Pwd) {
            this.Guid = Guid;
            this.Name = Name;
            this.Pwd = Pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginOnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginOnResponse", Namespace="http://XY.org/", Order=0)]
        public TEST1.SR.LoginOnResponseBody Body;
        
        public LoginOnResponse() {
        }
        
        public LoginOnResponse(TEST1.SR.LoginOnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://XY.org/")]
    public partial class LoginOnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginOnResult;
        
        public LoginOnResponseBody() {
        }
        
        public LoginOnResponseBody(string LoginOnResult) {
            this.LoginOnResult = LoginOnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountInfo", Namespace="http://XY.org/", Order=0)]
        public TEST1.SR.GetAccountInfoRequestBody Body;
        
        public GetAccountInfoRequest() {
        }
        
        public GetAccountInfoRequest(TEST1.SR.GetAccountInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://XY.org/")]
    public partial class GetAccountInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Guid;
        
        public GetAccountInfoRequestBody() {
        }
        
        public GetAccountInfoRequestBody(string Guid) {
            this.Guid = Guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountInfoResponse", Namespace="http://XY.org/", Order=0)]
        public TEST1.SR.GetAccountInfoResponseBody Body;
        
        public GetAccountInfoResponse() {
        }
        
        public GetAccountInfoResponse(TEST1.SR.GetAccountInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://XY.org/")]
    public partial class GetAccountInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TEST1.SR.Account GetAccountInfoResult;
        
        public GetAccountInfoResponseBody() {
        }
        
        public GetAccountInfoResponseBody(TEST1.SR.Account GetAccountInfoResult) {
            this.GetAccountInfoResult = GetAccountInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLotteryListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLotteryList", Namespace="http://XY.org/", Order=0)]
        public TEST1.SR.GetLotteryListRequestBody Body;
        
        public GetLotteryListRequest() {
        }
        
        public GetLotteryListRequest(TEST1.SR.GetLotteryListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://XY.org/")]
    public partial class GetLotteryListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Guid;
        
        public GetLotteryListRequestBody() {
        }
        
        public GetLotteryListRequestBody(string Guid) {
            this.Guid = Guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLotteryListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLotteryListResponse", Namespace="http://XY.org/", Order=0)]
        public TEST1.SR.GetLotteryListResponseBody Body;
        
        public GetLotteryListResponse() {
        }
        
        public GetLotteryListResponse(TEST1.SR.GetLotteryListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://XY.org/")]
    public partial class GetLotteryListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TEST1.SR.WS_Lotterys[] GetLotteryListResult;
        
        public GetLotteryListResponseBody() {
        }
        
        public GetLotteryListResponseBody(TEST1.SR.WS_Lotterys[] GetLotteryListResult) {
            this.GetLotteryListResult = GetLotteryListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLotteryPlayListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLotteryPlayList", Namespace="http://XY.org/", Order=0)]
        public TEST1.SR.GetLotteryPlayListRequestBody Body;
        
        public GetLotteryPlayListRequest() {
        }
        
        public GetLotteryPlayListRequest(TEST1.SR.GetLotteryPlayListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://XY.org/")]
    public partial class GetLotteryPlayListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LotteryType;
        
        public GetLotteryPlayListRequestBody() {
        }
        
        public GetLotteryPlayListRequestBody(string Guid, string LotteryType) {
            this.Guid = Guid;
            this.LotteryType = LotteryType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLotteryPlayListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLotteryPlayListResponse", Namespace="http://XY.org/", Order=0)]
        public TEST1.SR.GetLotteryPlayListResponseBody Body;
        
        public GetLotteryPlayListResponse() {
        }
        
        public GetLotteryPlayListResponse(TEST1.SR.GetLotteryPlayListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://XY.org/")]
    public partial class GetLotteryPlayListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TEST1.SR.LotteryPlays[] GetLotteryPlayListResult;
        
        public GetLotteryPlayListResponseBody() {
        }
        
        public GetLotteryPlayListResponseBody(TEST1.SR.LotteryPlays[] GetLotteryPlayListResult) {
            this.GetLotteryPlayListResult = GetLotteryPlayListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TEST1.SR.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TEST1.SR.WebService1Soap>, TEST1.SR.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TEST1.SR.HelloWorldResponse TEST1.SR.WebService1Soap.HelloWorld(TEST1.SR.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TEST1.SR.HelloWorldRequest inValue = new TEST1.SR.HelloWorldRequest();
            inValue.Body = new TEST1.SR.HelloWorldRequestBody();
            TEST1.SR.HelloWorldResponse retVal = ((TEST1.SR.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TEST1.SR.LoginOnResponse TEST1.SR.WebService1Soap.LoginOn(TEST1.SR.LoginOnRequest request) {
            return base.Channel.LoginOn(request);
        }
        
        public string LoginOn(string Guid, string Name, string Pwd) {
            TEST1.SR.LoginOnRequest inValue = new TEST1.SR.LoginOnRequest();
            inValue.Body = new TEST1.SR.LoginOnRequestBody();
            inValue.Body.Guid = Guid;
            inValue.Body.Name = Name;
            inValue.Body.Pwd = Pwd;
            TEST1.SR.LoginOnResponse retVal = ((TEST1.SR.WebService1Soap)(this)).LoginOn(inValue);
            return retVal.Body.LoginOnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TEST1.SR.GetAccountInfoResponse TEST1.SR.WebService1Soap.GetAccountInfo(TEST1.SR.GetAccountInfoRequest request) {
            return base.Channel.GetAccountInfo(request);
        }
        
        public TEST1.SR.Account GetAccountInfo(string Guid) {
            TEST1.SR.GetAccountInfoRequest inValue = new TEST1.SR.GetAccountInfoRequest();
            inValue.Body = new TEST1.SR.GetAccountInfoRequestBody();
            inValue.Body.Guid = Guid;
            TEST1.SR.GetAccountInfoResponse retVal = ((TEST1.SR.WebService1Soap)(this)).GetAccountInfo(inValue);
            return retVal.Body.GetAccountInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TEST1.SR.GetLotteryListResponse TEST1.SR.WebService1Soap.GetLotteryList(TEST1.SR.GetLotteryListRequest request) {
            return base.Channel.GetLotteryList(request);
        }
        
        public TEST1.SR.WS_Lotterys[] GetLotteryList(string Guid) {
            TEST1.SR.GetLotteryListRequest inValue = new TEST1.SR.GetLotteryListRequest();
            inValue.Body = new TEST1.SR.GetLotteryListRequestBody();
            inValue.Body.Guid = Guid;
            TEST1.SR.GetLotteryListResponse retVal = ((TEST1.SR.WebService1Soap)(this)).GetLotteryList(inValue);
            return retVal.Body.GetLotteryListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TEST1.SR.GetLotteryPlayListResponse TEST1.SR.WebService1Soap.GetLotteryPlayList(TEST1.SR.GetLotteryPlayListRequest request) {
            return base.Channel.GetLotteryPlayList(request);
        }
        
        public TEST1.SR.LotteryPlays[] GetLotteryPlayList(string Guid, string LotteryType) {
            TEST1.SR.GetLotteryPlayListRequest inValue = new TEST1.SR.GetLotteryPlayListRequest();
            inValue.Body = new TEST1.SR.GetLotteryPlayListRequestBody();
            inValue.Body.Guid = Guid;
            inValue.Body.LotteryType = LotteryType;
            TEST1.SR.GetLotteryPlayListResponse retVal = ((TEST1.SR.WebService1Soap)(this)).GetLotteryPlayList(inValue);
            return retVal.Body.GetLotteryPlayListResult;
        }
    }
}
